#BASIC CONFIG FOR PROMPT
#SHOW SERVER NAME AND CURRRENT PATH IN PROMPT

#SERVER NAME IS USEFULL FOR FAST VISUALIZATION WHAT SERVER YOU ARE
SERVERNAME="SERVERNAME"

# colors
DULL=0
BRIGHT=1
FG_BLACK=30
FG_YELLOW=33
FG_WHITE=37
BG_NULL=00
FG_GREEN=32

# ANSI Escape Commands
ESC="\033"
RESET="\[$ESC[${DULL};${FG_WHITE};${BG_NULL}m\]"
GREEN="\[$ESC[${DULL};${FG_GREEN}m\]"

umask 002
PS1="\n\[\033[1;30;33m$SERVERNAME\]$RESET [\w] \n $RESET\$ "
